version: "3.9"
services:
  db:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
  db-adminer:
    image: adminer
    restart: always
    ports:
    - "9090:8080"
